EXTRA_CFLAGS   += 

obj-$(CONFIG_RALINK_FLASH_API)	+= flash_api.o
flash_api-objs					:= flash_main.o mii_mgr_main.o rt3052_access.o
#flash_api-objs					:= flash_main.o rt3052_access.o
#flash_api-objs					:= flash_main.o flash_ioctl.o mii_mgr_main.o
