/*
 * Automatically generated header file, don't edit!
 */
#define ELBOX_HAVE_DOT_CONFIG 1
#define ELBOX_FIRMWARE_VERSION "2.03"
#define ELBOX_FIRMWARE_REVISION "N/A"

/* Device Configuration */
#define ELBOX_FIRMWARE_SIGNATURE "N/A"
#undef  ELBOX_BOARD_DEFAULT
#undef  ELBOX_BOARD_WMXRG01E
#undef  ELBOX_BOARD_WMXRG02E
#undef  ELBOX_BOARD_WMXCO02E
#undef  ELBOX_BOARD_WAPG14
#undef  ELBOX_BOARD_WAPG18
#undef  ELBOX_BOARD_WAPN03
#undef  ELBOX_BOARD_WAPN06
#undef  ELBOX_BOARD_WAPN07
#undef  ELBOX_BOARD_WAPN09
#undef  ELBOX_BOARD_WAPND01
#undef  ELBOX_BOARD_WAPND02
#undef  ELBOX_BOARD_WAPND03
#undef  ELBOX_BOARD_WAPND04
#undef  ELBOX_BOARD_WAPND06
#undef  ELBOX_BOARD_WRGG14
#undef  ELBOX_BOARD_WRGG14C
#undef  ELBOX_BOARD_WRGG15C
#undef  ELBOX_BOARD_WRGG16
#undef  ELBOX_BOARD_WRGG19
#undef  ELBOX_BOARD_WRGG19_C
#undef  ELBOX_BOARD_WRGG19_C_ART
#undef  ELBOX_BOARD_WRGG19_C_HSPOT
#undef  ELBOX_BOARD_WRGG22
#undef  ELBOX_BOARD_WRGG23
#undef  ELBOX_BOARD_WRGG24
#undef  ELBOX_BOARD_WRGG27
#undef  ELBOX_BOARD_WRGG27HP
#undef  ELBOX_BOARD_WRGG27_3G
#undef  ELBOX_BOARD_RT3052
#undef  ELBOX_BOARD_WRGN06
#undef  ELBOX_BOARD_WRGN06C
#undef  ELBOX_BOARD_WRGN09
#undef  ELBOX_BOARD_WRGN10
#undef  ELBOX_BOARD_WRGN13
#undef  ELBOX_BOARD_WRGN15
#undef  ELBOX_BOARD_WRGN15C
#undef  ELBOX_BOARD_WRGN16
#undef  ELBOX_BOARD_WRGN16A
#undef  ELBOX_BOARD_WRGN18
#undef  ELBOX_BOARD_WRGN18N
#undef  ELBOX_BOARD_SWRGN18
#undef  ELBOX_BOARD_WRGN19
#undef  ELBOX_BOARD_WRGN20
#undef  ELBOX_BOARD_WRGN22
#undef  ELBOX_BOARD_WRGN22S
#define ELBOX_BOARD_WRGN23 1
#undef  ELBOX_BOARD_WRGN23I
#undef  ELBOX_BOARD_WRGN23TD
#undef  ELBOX_BOARD_WRGN23HA
#undef  ELBOX_BOARD_WRGN27
#undef  ELBOX_BOARD_WRGN27U
#undef  ELBOX_BOARD_WRGN28
#undef  ELBOX_BOARD_WRGN29
#undef  ELBOX_BOARD_WRGND02
#undef  ELBOX_BOARD_WRGND03
#undef  ELBOX_BOARD_WRGND04
#undef  ELBOX_BOARD_WRGND06
#undef  ELBOX_BOARD_WRGND07
#undef  ELBOX_BOARD_WRGND08
#undef  ELBOX_BOARD_WRGNS01
#undef  ELBOX_BOARD_WTDRG01
#undef  ELBOX_BOARD_WTDRV01
#undef  ELBOX_BOARD_WHDRV01
#undef  ELBOX_BOARD_WRGN33
#define ELBOX_BOARD_NAME "wrgn23"
#define ELBOX_BSP_RT305X 1
#define ELBOX_WRGN23_WAN_UP_DETECT_BY_INTERRUPT 1
#undef  ELBOX_WRGN23_DISABLE_QUICKGAMESTART_BUTTON
#define ELBOX_BSP_NAME "rt305x"
#define ELBOX_LINUX_MAJOR 2
#define ELBOX_LINUX_MINOR 6
#define ELBOX_LINUX_BUILD 21
#undef  ELBOX_INSTALL_LIBGCC_A_SO
#define ELBOX_TEMPLATE_GW_WIFI 1
#undef  ELBOX_TEMPLATE_GW_WIFI_2WAN
#undef  ELBOX_TEMPLATE_AP_WIFI
#undef  ELBOX_TEMPLATE_AP_GW_WIFI
#undef  ELBOX_TEMPLATE_AP_GAMING
#undef  ELBOX_TEMPLATE_AP_WIFI_WAN
#undef  ELBOX_TEMPLATE_TENDER
#undef  ELBOX_TEMPLATE_EMPTY
#undef  ELBOX_TEMPLATE_ARIES
#define ELBOX_TEMPLATE_NAME "gw.wifi"
#define ELBOX_BRAND_NAME "dlwbr"
#define ELBOX_MODEL_NAME "dir600b"
#undef  ELBOX_TEMPLATE_GW_WIFI_GZONE
#undef  ELBOX_BRAND_GENERIC
#undef  ELBOX_BRAND_SEATTLE
#define ELBOX_BRAND_DLWBR 1
#undef  ELBOX_BRAND_AIRLINK
#undef  ELBOX_BRAND_CONCEPTRONIC
#undef  ELBOX_MODEL_DIR300
#undef  ELBOX_MODEL_DIR300B
#undef  ELBOX_MODEL_DIR300B_ORANGE
#undef  ELBOX_MODEL_DIR300B_SZT
#undef  ELBOX_MODEL_DIR300SZT
#undef  ELBOX_MODEL_DIR300ENTEL
#undef  ELBOX_MODEL_DIR300TELGUA
#undef  ELBOX_MODEL_DIR320
#undef  ELBOX_MODEL_DIR605
#undef  ELBOX_MODEL_DIR605B
#undef  ELBOX_MODEL_DIR615
#undef  ELBOX_MODEL_DIR320HP
#undef  ELBOX_MODEL_DIR465
#undef  ELBOX_MODEL_DIR815
#undef  ELBOX_MODEL_DIR685
#undef  ELBOX_MODEL_DIR605D1
#define ELBOX_MODEL_DIR600B 1
#undef  ELBOX_MODEL_DIR600B_Cablevision
#undef  ELBOX_MODEL_DIR600B_Axtel
#undef  ELBOX_MODEL_DIR600B_Megacable
#undef  ELBOX_MODEL_DIR600B_DNETelenet
#undef  ELBOX_MODEL_DIR617
#undef  ELBOX_MODEL_DIR627

/* Brand/Model Selection */

/* Features configuration */
#define LOGNUM 1
#undef  ELBOX_USE_IPV6

/* Language Configuration */

/* Language options */
#define ELBOX_CREATE_LANGUAGE_PACK 1

/* Languages */
#undef  ELBOX_LANGUAGE_JA
#define ELBOX_LANGUAGE_DE 1
#define ELBOX_LANGUAGE_ZH_TW 1
#define ELBOX_LANGUAGE_ZH_CN 1
#define ELBOX_LANGUAGE_FR 1
#undef  ELBOX_LANGUAGE_ES
#undef  ELBOX_LANGUAGE_IT
#undef  ELBOX_LANGUAGE_NL
#undef  ELBOX_LANGUAGE_PT
#undef  ELBOX_LANGUAGE_FI
#undef  ELBOX_LANGUAGE_SV
#undef  ELBOX_LANGUAGE_NO
#undef  ELBOX_LANGUAGE_DA
#define ELBOX_LANGUAGE_KO 1
#undef  ELBOX_LANGUAGE_PL
#define ELBOX_LANGUAGE_RU 1
#undef  ELBOX_LANGUAGE_HE
#undef  ELBOX_LANGUAGE_HU
#undef  ELBOX_LANGUAGE_EL
#undef  ELBOX_LANGUAGE_TR
#undef  ELBOX_LANGUAGE_CS
#undef  ELBOX_LANGUAGE_TH
#undef  ELBOX_LANGUAGE_AR
#undef  ELBOX_LANGUAGE_IS

/* Default Language */

/* Programs Configuration */

/* GPL Programs */

/* ------------------------ Busybox ------------------------ --- */
#define ELBOX_BUSYBOX 1
#define ELBOX_PROGS_GPL_BUSYBOX_1_00 1
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_11_1
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_14_1
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_00_ADVANCED_CONFIG
#undef  ELBOX_PROGS_GPL_TFTP_FTP_GET_PUT_FW_CONFIG
#undef  ELBOX_BUSYBOX_DYNAMIC_LINKING
#undef  ELBOX_BUSYBOX_HAVE_MDEV
#undef  ELBOX_BUSYBOX_USE_FANCY_PING

/* ------------------------ Programs ----------------------- --- */
#undef  ELBOX_ARP_SPOOF
#undef  ELBOX_PROGS_GPL_BPALOGIN
#undef  ELBOX_PROGS_GPL_CHILLISPOT
#undef  ELBOX_PROGS_GPL_DIBBLER
#define ELBOX_USE_DNS 1
#define ELBOX_PROGS_GPL_DNRD_2_10 1
#undef  ELBOX_PROGS_GPL_DNSMASQ
#undef  ELBOX_HOSTAPD
#define ELBOX_HTTPD 1
#define ELBOX_PROGS_GPL_MATHOPD 1
#undef  ELBOX_PROGS_GPL_MATHOPD_STANDARD
#undef  ELBOX_PROGS_GPL_MATHOPD_16

/* Upload externel file */
#undef  ELBOX_PROGS_GPL_MATHOPD_EXTERNAL_FILE
#undef  ELBOX_PROGS_GPL_MATHOPD_ACL_IMPORT
#undef  ELBOX_PROGS_GPL_MATHOPD_EXTERNAL_BT_FILE
#undef  ELBOX_PROGS_GPL_IGMPPROXY
#define ELBOX_PROGS_GPL_IPPERSONALITY 1
#define ELBOX_PROGS_GPL_IPROUTE2_2_6_8 1
#undef  ELBOX_PROGS_GPL_TC_FOR_AP
#undef  ELBOX_PROGS_GPL_TC_U32_IP_PORT_RANGE
#define ELBOX_IPTABLES 1
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_6A
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_7A
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_9
#define ELBOX_PROGS_GPL_IPTABLES_1_3_5 1
#undef  ELBOX_IPTABLES_L7_EXT
#undef  ELBOX_PROGS_GPL_ITUNES_SERVER
#define ELBOX_KLOGD 1
#define ELBOX_PROGS_GPL_KLOGD 1
#undef  ELBOX_PROGS_GPL_KLOGD_AP
#undef  ELBOX_PROGS_GPL_LPRNG_3_8_27
#define ELBOX_PROGS_GPL_NSBBOX 1

/* NotSoBusyBOX configuration */
#undef  CONFIG_NSBBOX_BASE64
#define CONFIG_NSBBOX_BRCTL 1
#define CONFIG_NSBBOX_BRCTL_BWCTRL 1
#undef  CONFIG_NSBBOX_BRCTL_IOAPNL
#define CONFIG_NSBBOX_BRCTL_PORTFORWARD 1
#undef  CONFIG_NSBBOX_BRCTL_PORTDENYLIST
#undef  CONFIG_NSBBOX_BRCTL_IGMP
#undef  CONFIG_NSBBOX_BRCTL_AP_OPERATION_MODE
#undef  CONFIG_NSBBOX_BRCTL_APC_OPERATION_MODE
#undef  CONFIG_NSBBOX_BRCTL_DHCP_SERVER_ENABLE
#undef  CONFIG_NSBBOX_BRCTL_E_PARTITION
#undef  CONFIG_NSBBOX_BRCTL_ETHLINK
#undef  CONFIG_NSBBOX_BRCTL_LIMITED_ADMIN
#undef  CONFIG_NSBBOX_BRCTL_PING_CONTROL
#undef  CONFIG_NSBBOX_BRCTL_MULTI_VLAN
#undef  CONFIG_NSBBOX_BRCTL_MAT_STATUS
#undef  CONFIG_NSBBOX_BRCTL_MAC_CLONE
#define CONFIG_NSBBOX_NTPCLIENT 1
#define CONFIG_NSBBOX_SMTPCLIENT 1
#define CONFIG_NSBBOX_VCONFIG 1
#define ELBOX_PPPD 1
#define ELBOX_PROGS_GPL_PPPD_ALPHA 1

/* Accelerate pptp */
#undef  ELBOX_PROGS_GPL_PPPD_ACCEL_PPTP
#undef  ELBOX_PROGS_GPL_PPPD_ACCEL_PPTP_PLUS
#undef  ELBOX_PROGS_GPL_PURE_FTPD
#undef  ELBOX_PROGS_GPL_QUOTA
#undef  ELBOX_PROGS_GPL_RADVD
#undef  ELBOX_SAMBA
#undef  ELBOX_PROGS_GPL_NET_SNMP
#undef  ELBOX_PROGS_GPL_STUPID_FTPD
#define ELBOX_USE_SYSLOG 1
#undef  ELBOX_PROGS_GPL_SYSLOGD
#define ELBOX_PROGS_GPL_SYSLOGD_V2 1
#undef  ELBOX_PROGS_GPL_SYSLOGD_REMOTELOG
#undef  ELBOX_PROGS_GPL_SYSLOGD_SMTP
#undef  ELBOX_PROGS_GPL_SYSLOGD_AP
#define ELBOX_PROGS_GPL_TELNETD 1
#undef  ELBOX_PROGS_GPL_TELNETD_CLIENT_CONNECTION_TIMEOUT
#undef  ELBOX_PROGS_GPL_TELNETD_GET_DATABASE
#undef  ELBOX_PROGS_GPL_TINYLOGIN
#undef  ELBOX_PROGS_GPL_TZCOMPILER
#undef  ELBOX_PROGS_GPL_UDEV
#define ELBOX_UDHCP 1

/* Use Unicasting and broadcasting request */
#define ELBOX_PROGS_GPL_UDHCP_REQUEST_BROADCAST 1
#undef  ELBOX_PROGS_GPL_UDHCP_0_9_8
#define ELBOX_PROGS_GPL_UDHCPCD 1
#undef  ELBOX_PROGS_GPL_UDHCP_RFC3442
#undef  ELBOX_PROGS_GPL_UDHCP_RFC2132
#undef  ELBOX_PROGS_GPL_UDHCP_HOLD_LAN_IP
#undef  ELBOX_PROGS_GPL_UPNPIGD
#undef  ELBOX_PROGS_GPL_USB_MODE_SWITCH
#undef  ELBOX_PROGS_GPL_WOL
#define ELBOX_PROGS_GPL_WIRELESS_TOOLS 1

/* IWLIST configuration */
#undef  CONFIG_IWLIST_APSCANN

/* IWPRIV configuration */
#undef  CONFIG_IWPRIV_APSCAN
#undef  ELBOX_PROGS_GPL_XSUPPLICANT
#undef  ELBOX_PROGS_GPL_ZEBRA
#undef  ELBOX_RADIUSCLIENT
#undef  ELBOX_PROGS_GPL_ECMH
#undef  ELBOX_PROGS_GPL_IPUTILS

/* ------------------------ Libraries ------------------------ --- */
#undef  ELBOX_FLEX
#undef  ELBOX_LIBNL
#define ELBOX_PROGS_GPL_LIB_GSASL 1
#define ELBOX_PROGS_GPL_LIB_GSASL_0_2_6 1
#undef  ELBOX_OPENSSL
#undef  ELBOX_PROGS_GPL_LIBTORRENT
#undef  ELBOX_ZLIB
#undef  ELBOX_PROGS_GPL_EMAILCLIENT

/* Private Programs (developed by AlphaNetworks) */
#undef  ELBOX_PROGS_PRIV_CALLMGR
#define ELBOX_XMLDB 1
#define ELBOX_PROGS_PRIV_XMLDB 1
#undef  ELBOX_PROGS_PRIV_XMLDB3
#define ELBOX_CREATE_RGDB_LINK_TO_XMLDBC 1
#define ELBOX_PROGS_PRIV_RGBIN 1

/* RGBIN configuration */

/* GPL tools - DO NOT use the GPL code here, use PROG.GPL/NSBBOX instead !! */
#undef  CONFIG_RGBIN_BASE64
#undef  CONFIG_RGBIN_BRCTL
#undef  CONFIG_RGBIN_PING_CONTROL_USE_PROC_FILE
#undef  CONFIG_RGBIN_NTPCLIENT
#undef  CONFIG_RGBIN_SMTPCLIENT
#undef  CONFIG_RGBIN_VCONFIG
#undef  CONFIG_RGBIN_BRCTL_WEB_REDIRECT

/* Private tools - ONLY use the private code here !! */
#undef  CONFIG_RGBIN_SEAMA
#undef  CONFIG_RGBIN_HTTPC
#undef  CONFIG_RGBIN_GENUUID
#define CONFIG_RGBIN_PFILE 1
#define CONFIG_RGBIN_SCUT 1
#define CONFIG_RGBIN_TLOGS 1
#define CONFIG_RGBIN_ASESSION 1
#undef  CONFIG_RGBIN_MPCONVERT
#define CONFIG_RGBIN_DAYCONVERT 1
#define CONFIG_RGBIN_CHNET 1
#undef  CONFIG_RGBIN_ROUTETABLE
#undef  CONFIG_RGBIN_PARSEINFO
#define CONFIG_RGBIN_LOGIN 1
#define CONFIG_RGBIN_ARPPING 1
#define CONFIG_RGBIN_GETHOSTIP 1
#undef  CONFIG_RGBIN_COREDE
#define CONFIG_RGBIN_USOCKC 1
#undef  CONFIG_RGBIN_SUSOCKC
#undef  CONFIG_RGBIN_RSTRCMP
#undef  CONFIG_RGBIN_GETSYS
#undef  CONFIG_RGBIN_USB3G_KIT
#undef  CONFIG_RGBIN_USBRESET
#undef  CONFIG_RGBIN_CHECK_CONNECTION
#undef  CONFIG_RGBIN_3GCHAT
#undef  CONFIG_RGBIN_IPV6IP
#undef  CONFIG_RGBIN_IPV6PDIP

/* DevData - Permanent Data */
#define CONFIG_RGBIN_DEVDATA 1
#define CONFIG_RGBIN_DEVDATA_MTDBLOCK "/dev/mtdblock/4"
#define CONFIG_RGBIN_DEVDATA_OFFSET 0x8000
#define CONFIG_RGBIN_DEVDATA_SIZE 0x8000

/* DevConf - User Configuration */
#define CONFIG_RGBIN_DEVCONF 1
#define CONFIG_RGBIN_DEVCONF_MTDBLOCK "/dev/mtdblock/3"
#define CONFIG_RGBIN_DEVCONF_OFFSET 0x0
#define CONFIG_RGBIN_DEVCONF_SIZE 0x10000

/* outdated utilities */
#undef  ELBOX_RGBIN_RGCFG
#undef  CONFIG_RGBIN_RGDB
#define CONFIG_RGBIN_TCPREQUEST 1
#undef  CONFIG_RGBIN_SCHEDULE_FOR_NTP_CONNECT_COUNTER
#define ELBOX_ALPHA_XGI 1
#define ELBOX_PROGS_PRIV_ALPHA_XGI 1
#undef  ELBOX_IPSEC_PT
#define ELBOX_IFRESETCNT 1
#undef  ELBOX_PROGS_PRIV_IFRESETCNT
#define ELBOX_PROGS_PRIV_IFRESETCNT_26 1
#undef  ELBOX_STUN_NAT
#define ELBOX_TURBONAT 1
#undef  ELBOX_PROGS_PRIV_TURBONAT
#define ELBOX_PROGS_PRIV_TURBONAT_26 1
#define ELBOX_PROGS_PRIV_TURBONAT_QOS 1
#define ELBOX_PROGS_PRIV_TURBONAT_UBCOM 1
#undef  ELBOX_PROGS_PRIV_BWC
#undef  ELBOX_PROGS_PRIV_FLOWMETER
#undef  ELBOX_PROGS_PRIV_APX
#define ELBOX_LOG_MESSAGE 1
#define ELBOX_PROGS_PRIV_LOG_ENGLISH 1
#undef  ELBOX_MADWIFI
#undef  ELBOX_PROGS_PRIV_ART_AP83
#undef  ELBOX_PROGS_PRIV_MADWIFI_AP83
#undef  ELBOX_PROGS_PRIV_MADWIFI_CAVIUM
#undef  ELBOX_PROGS_PRIV_MADWIFI_FUSION_CAVIUM
#undef  ELBOX_PROGS_PRIV_MADWIFI_FUSION_CAVIUM_SEATTLE
#undef  ELBOX_RALINK_WIFI
#undef  ELBOX_PROGS_PRIV_WLXMLPATCH_RALINK
#undef  ELBOX_PROGS_PRIV_WLKLOGDPATCH_RALINK
#undef  ELBOX_PROGS_PRIV_RALINK_INIC
#define ELBOX_RT2860V2 1
#undef  ELBOX_PROGS_PRIV_RT2860V2
#define ELBOX_PROGS_PRIV_RT2860V2_V1900 1
#undef  ELBOX_PROGS_PRIV_RT2860V2_V3200
#undef  ELBOX_PROGS_PRIV_RT2860V2_V2200
#undef  ELBOX_PROGS_PRIV_RT2860V2_V2300
#undef  ELBOX_PROGS_PRIV_RT2860V2_LED_DRIVE
#undef  ELBOX_PROGS_PRIV_RT2860V2_STA
#undef  ELBOX_PROGS_PRIV_RT2860V2_WLAN_PARTITION
#undef  ELBOX_PROGS_PRIV_RT2860V2_PRIORITYBYPORT
#undef  ELBOX_PROGS_PRIV_RT2860V2_MAC_CLONE
#undef  ELBOX_PROGS_PRIV_RTL8366S_GREENT_ETHERNET
#undef  ELBOX_RT2561
#undef  ELBOX_BROADCOM_WIFI
#undef  ELBOX_PROGS_PRIV_RALINK_RT3090
#undef  ELBOX_PROGS_PRIV_RALINK_RT3883_3662
#undef  ELBOX_SAMSUNG_EZLINK
#define ELBOX_PROGS_PRIV_UPNPKITS 1

/* UPnP kits configuration */
#define CONFIG_UPNPKITS_HNAP 1
#define CONFIG_UPNPKITS_UPNPKITS 1
#define CONFIG_UPNPKITS_UPNPDEV 1
#define CONFIG_UPNPKITS_WFADEV 1
#define CONFIG_UPNPKITS_WFANOTIFY 1
#define CONFIG_UPNPKITS_WFANOTIFY_SERVICE_ROOT_NODE "/runtime/upnpdev/root:2/service:1"
#undef  CONFIG_UPNPKITS_UPNPCP
#undef  CONFIG_UPNPKITS_COREGA_ROUTER
#define CONFIG_UPNPKITS_GENUUID 1
#define ELBOX_PROGS_PRIV_NEAPS 1

/* Neap Server Class Configuration */
#define CONFIG_NEAPS_INTERNET 1
#define CONFIG_NEAPS_WIRELESS 1
#define CONFIG_NEAPS_RESIDENTIAL_GATEWAY 1
#undef  ELBOX_PROGS_PRIV_AP_NEAP
#undef  ELBOX_PROGS_PRIV_IGMP
#define ELBOX_PROGS_PRIV_IGMPPROXY 1

/* igmpproxy configuration */
#define ELBOX_PROGS_PRIV_IGMPPROXY_IGMPV3 1
#define ELBOX_PROGS_PRIV_SCHEDULED 1
#define ELBOX_PROGS_PRIV_COMMON_SCRIPTS 1

/* 3g support */
#undef  ELBOX_PROGS_PRIV_COMMON_SCRIPTS_3G_PLUG_AND_PLAY
#undef  ELBOX_PROGS_PRIV_COMMON_SCRIPTS_UDEV_USB_3G_HOTPLUG
#define ELBOX_PROGS_PRIV_DHCPXMLPATCH 1
#undef  ELBOX_PROGS_PRIV_UPDATELEASES
#undef  ELBOX_PROGS_PRIV_MTDTEST
#define ELBOX_PROGS_PRIV_PORTT 1
#undef  ELBOX_PROGS_PRIV_NETSTAR
#undef  ELBOX_PROGS_PRIV_RESOLVED
#undef  ELBOX_PROGS_PRIV_PROXYD
#define ELBOX_DDNS 1

/* Select DDNS updater implementation */
#define ELBOX_PROGS_PRIV_DYNDNS 1
#define ELBOX_PROGS_PRIV_PEANUT 1
#undef  ELBOX_PROGS_PRIV_BDTOOL
#undef  ELBOX_PROGS_PRIV_BDCFG
#define ELBOX_PROGS_PRIV_LLD2D 1
#undef  ELBOX_PROGS_PRIV_CMCGI
#undef  ELBOX_PROGS_PRIV_ART
#define ELBOX_PROGS_PRIV_WIDGET 1
#undef  ELBOX_PROGS_PRIV_WIDGETV2
#undef  ELBOX_PROGS_PRIV_TR069_CLIENT
#undef  ELBOX_PROGS_PRIV_TRAFFICCTRL
#undef  ELBOX_PROGS_PRIV_ALPHA_HOTPLUG
#undef  ELBOX_PROGS_PRIV_WCN_UFD
#undef  ELBOX_PROGS_PRIV_MADWIFI_DUALBAND
#undef  ELBOX_PROGS_PRIV_ALPHA_NLS_DRV
#define ELBOX_PROGS_PRIV_WPSTOOLS 1

/* WPS tools configuration */
#undef  CONFIG_WPSTOOLS_BIG_ENDIAN
#define CONFIG_WPSTOOLS_PROFILE_HELPER 1
#undef  CONFIG_WPSTOOLS_USE_SHARED_OPENSSL
#undef  CONFIG_WPSTOOLS_STA_SUPPORT
#undef  CONFIG_WPSTOOLS_ALPHA_BACKUP_RADIUS_SERVER
#undef  CONFIG_WPSTOOLS_ALPHA_NAP_SERVER_SUPPORT
#undef  CONFIG_WPSTOOLS_ALPHA_UNSUPPORT_PRAGMA_PACK
#undef  CONFIG_WPSTOOLS_RADIUS_SERVER_ON_BOARD
#undef  CONFIG_WPSTOOLS_DISABLE_HOSTAPD
#undef  CONFIG_WPSTOOLS_ALPHA_MAC_BASE_RADIUS_SUPPORT
#undef  ELBOX_PROGS_PRIV_WPA_SUPPLICANT
#undef  ELBOX_PROGS_PRIV_WPA_SUPPLICANT_0_5
#undef  ELBOX_PROGS_PRIV_CAPWAP
#undef  ELBOX_PROGS_PRIV_CLI
#undef  ELBOX_PROGS_PRIV_CLI_VER2
#undef  ELBOX_FIRMWARE_HEADER_VERSION_CONTROL
#define ELBOX_WLXMLPATCHV2 1
#define ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK 1
#undef  ELBOX_PROGS_PRIV_WLXMLPATCHV2_MADWIFI

/* Ralink model selection */
#define ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK_RT2800 1
#undef  ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK_RT61
#undef  ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK_RT2880
#undef  ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK_RT2880_v1183
#undef  ELBOX_PROGS_PRIV_NETBIOS
#undef  ELBOX_PROGS_PRIV_ETHLINK
#define ELBOX_PROGS_PRIV_SENDMAIL 1
#undef  ELBOX_PROGS_PRIV_STATIC_DHCP
#undef  ELBOX_PROGS_PRIV_SERVD
#undef  ELBOX_PROGS_PRIV_CGIBIN_ARIES
#undef  ELBOX_PROGS_PRIV_UPNP_AV
#define ELBOX_PROGS_PRIV_VERIFICATION_CODE 1
#undef  ELBOX_PROGS_PRIV_CLONED
#undef  ELBOX_PROGS_PRIV_LOGD
#undef  ELBOX_PROGS_PRIV_IODATA_QUICKCOPY
#undef  ELBOX_PROGS_PRIV_IODATA_QUICKCOPY_CLIENT
#undef  ELBOX_PROGS_PRIV_DDNSD
#undef  ELBOX_PROGS_PRIV_DHCPPLUS
#define ELBOX_PROGS_PRIV_STARSPEED 1

/* Star Speed configuration */
#define CONFIG_STARSPEED_HUBEI 1
#define CONFIG_STARSPEED_XIAN 1
#define CONFIG_STARSPEED_HENAN 1
#define CONFIG_STARSPEED_NANCHANG_CAMPUS 1
#undef  ELBOX_PROGS_PRIV_TRAP_MONITOR
#undef  ELBOX_PROGS_PRIV_AUTOREKEY
#undef  ELBOX_PROGS_PRIV_ALPHA_3GTOOL
#undef  ELBOX_PROGS_PRIV_WEBREDIRECT
#undef  ELBOX_PROGS_PRIV_WFI_INV
#undef  ELBOX_PROGS_PRIV_IGMP_2_6_27
#undef  ELBOX_PROGS_PRIV_USBOVERIP
#undef  ELBOX_PROGS_PRIV_RALINK_REPEATER
#undef  ELBOX_PROGS_PRIV_RALINK_SCAN
#undef  ELBOX_PROGS_PRIV_LLMNRESP
#undef  ELBOX_PROGS_PRIV_WEPCLIENTINFOPATCH
#undef  ELBOX_PROGS_PRIV_MADWIFI_AR724X
#undef  ELBOX_UPDATEWIFISTATS
#undef  ELBOX_PROGS_PRIV_RTSTAD
#undef  PROGS_PRIV_ATHEROS_SECURITY_VERSION

/* Common library configuration */
#define ELBOX_COMLIB_MEM_HELPER_DISABLE 1
