#!/bin/sh
case "$1" in
save)
	/etc/scripts/dbsave.sh
	;;
init)
	LANMAC=`echo -e $2 | tr [A-Z] [a-z]`
	LANMAC2=`echo -e $3 | tr [A-Z] [a-z]`
	WANMAC=`echo -e $4 | tr [A-Z] [a-z]`
	CCODE="$5"
	IP="$6"
	PIN="$7"
	PSK="$8"
	[ "$LANMAC" != "" ] && DEVDATA="$DEVDATA -e lanmac=$LANMAC -e wlanmac=$LANMAC"
	[ "$LANMAC2" != "" ] && DEVDATA="$DEVDATA -e lanmac2=$LANMAC2"
	[ "$WANMAC" != "" ] && DEVDATA="$DEVDATA -e wanmac=$WANMAC"
	[ "$CCODE" = "" ] && CCODE="US"
	[ "$PIN" != "" ] && DEVDATA="$DEVDATA -e pin=$PIN"
	[ "$PSK" != "" ] && DEVDATA="$DEVDATA -e psk=$PSK"
	echo "devdata set -e countrycode=$CCODE $DEVDATA -f" > /dev/console
	devdata set -e countrycode=$CCODE $DEVDATA -f
	# Save wireless MAC address to EEPROM
	M1=`echo $LANMAC | cut -d: -f1`
	M2=`echo $LANMAC | cut -d: -f2`
	M3=`echo $LANMAC | cut -d: -f3`
	M4=`echo $LANMAC | cut -d: -f4`
	M5=`echo $LANMAC | cut -d: -f5`
	M6=`echo $LANMAC | cut -d: -f6`
	iwpriv ra0 e2p 04=$M2$M1
	iwpriv ra0 e2p 06=$M4$M3
	iwpriv ra0 e2p 08=$M6$M5
	# Set MAC Address and IP Address into u-boot config.
	[ "$LANMAC" != "" ] && UBCFG="$UBCFG ethaddr=$LANMAC"
	[ "$IP" != "" ] && UBCFG="$UBCFG ipaddr=$IP"
	echo "ubcfg set $UBCFG" > /dev/console
	ubcfg set $UBCFG
	# Show devdata and uboot data
	echo "-------- devdata dump ----------------------" > /dev/console
	devdata dump > /dev/console
	echo "-------- ubcfg get ethaddr ipaddr-----------" > /dev/console
	ubcfg get ethaddr ipaddr > /dev/console
	echo "--------------------------------------------" > /dev/console
	;;
evm)
	if [ $# -ne 9 ]; then
		echo "usage:"
		echo "  mfc evm ATETXMODE ATETXMCS ATECHANNEL ATETXLEN ATETXBW ATETXFREQOFFSET ATETXPOW0 ATETXPOW1"
		exit 1
	fi
	iwpriv ra0 set ATE=ATESTART
	iwpriv ra0 set ATETXMODE=$2
	iwpriv ra0 set ATETXMCS=$3
	iwpriv ra0 set ATECHANNEL=$4
	iwpriv ra0 set ATETXLEN=$5
	iwpriv ra0 set ATETXBW=$6
	iwpriv ra0 set ATETXCNT=1000000000000
	iwpriv ra0 set ATETXFREQOFFSET=$7
	iwpriv ra0 set ATETXPOW0=$8
	iwpriv ra0 set ATETXPOW1=$9
	iwpriv ra0 set ATE=TXFRAME
	;;
wlan)
	iwpriv ra0 set AuthMode=OPEN
	iwpriv ra0 set EncrypType=NONE
	iwpriv ra0 set Channel=$3
	iwpriv ra0 set SSID=$2
	;;
wlan2)
	iwpriv ra1 set AuthMode=OPEN
	iwpriv ra1 set EncrypType=NONE
	iwpriv ra1 set HideSSID=0
	iwpriv ra1 set Channel=$3
	iwpriv ra1 set AccessPolicy=0
	iwpriv ra1 set ACLClearAll=1
	iwpriv ra1 set SSID=$2
	;;
dump)
	devdata dump
	;;
ver)
	echo Ver `cat /etc/config/buildver` Build `cat /etc/config/buildno`
	;;
get)
	[ "$2" != "" ] && devdata get -e $2
	;;
freset)
	devconf del
	;;
button)
	case $2 in
	reset)
		usockc /var/gpio_ctrl GPIO_FRESET
		cat /var/gpio_ctrl_result
		;;
	wps)
		usockc /var/gpio_ctrl GPIO_WPSPBC
		cat /var/gpio_ctrl_result
		;;
	esac
	;;
led)
	case "$2" in
	wps_blue)
		usockc /var/gpio_ctrl WPS_BLUE
		;;
	wps_red)
		usockc /var/gpio_ctrl WPS_RED
		;;
	status_green)
		usockc /var/gpio_ctrl STATUS_GREEN
		;;
	status_amber)
		usockc /var/gpio_ctrl STATUS_AMBER
		;;
	inet_green)
		usockc /var/gpio_ctrl INET_GREEN
		;;
	inet_amber)
		usockc /var/gpio_ctrl INET_AMBER
		;;
	esac
	;;
*)
	echo "Usage: mfc {command} <params>"
	echo "Commands:"
	echo "  init <lanmac1> <lanmac2> <wanmac> <countrycode> <deviceip> <pin> <psk>"
	echo "                           Init flash"
	echo "  save                     Save current setting to flash"
	echo ""
	echo "  evm <ATETXMODE> <ATETXMCS> <ATECHANNEL> <ATETXLEN> <ATETXBW>"
	echo "      <ATETXFREQOFFSET> <ATETXPOW0> <ATETXPOW1>"
	echo "                           burn the ATE wireless parameters in to the EEPROM"
	echo ""
	echo "  wlan  <ssid>  <channel>  switch ssid  and channel"
	echo "  wlan2 <ssid2> <channel>  switch ssid2 and channel"
	echo "  dump                     Dump environment vairables."
	echo "  ver                      Show firmware version"
	echo ""
	echo "  get <name>               Get current WAN mac address"
	echo "  freset                   Factory reset"
	echo ""
	echo "  test on                  turn on test mode"
	echo "  test off                 turn off test mode"
	echo ""
	echo "  button {reset|wps}"
	echo "      reset                Get factory reset button status."
	echo "      wps                  Get WPS button status."
	echo ""
	echo "  led {wps_blue|wps_red|status_green|status_amber|inet_green|inet_amber}"
	echo "      wps_blue             Turn on WPS blue led."
	echo "      wps_red              Turn on WPS red led."
	echo "      status_green         Turn on power/status green led."
	echo "      status_amber         Turn on power/status amber led."
	echo "      inet_green           Turn on internet green led."
	echo "      inet_amber           Turn on internet amber led."
	;;
esac
